---
abstract: 'Subclass of L<Plack::Request> which supports encoding.'
author:
  - 'moznion <moznion@gmail.com>'
build_requires:
  HTTP::Request: 0
  HTTP::Request::Common: 0
  Plack::Test: 0
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.8.1, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Request-WithEncoding
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Plack::Request::WithEncoding:
    file: lib/Plack/Request/WithEncoding.pm
    version: 0.10
requires:
  Encode: 0
  Hash::MultiValue: 0
  Plack::Request: 0
  parent: 0
  perl: 5.008001
resources:
  bugtracker: https://github.com/moznion/Plack-Request-WithEncoding/issues
  homepage: https://github.com/moznion/Plack-Request-WithEncoding
  repository: git://github.com/moznion/Plack-Request-WithEncoding
version: 0.10
x_contributors:
  - 'Songmu <y.songmu@gmail.com>'
